"""Project activity-log projection (AS-WP-003 Phase 5; AS-013, AS-014).

The log is a deterministic projection of routing state, rendered
inside one ``activity-log`` generated region. Entries are keyed by
stable event ID, ordered newest-first by (occurred_at, event_id);
replays render byte-identical content, so no duplicate entries can
ever appear and unchanged logs are never rewritten.
"""

from __future__ import annotations

from internal import atlas_links, generated_regions
from internal.routing_state import ProjectRoutingState, RoutedEventRecord

LOG_REGION = "activity-log"


def _sort_key(record: RoutedEventRecord) -> tuple[str, str]:
    return (record.occurred_at, record.event_id)


def render_log_entries(
    state: ProjectRoutingState, *, from_file_rel: str, project_rel: str
) -> str:
    """Render all log entries newest-first."""
    blocks: list[str] = []
    records = sorted(state.routed_events.values(), key=_sort_key, reverse=True)
    for record in records:
        year, month, day = record.occurred_at[:4], record.occurred_at[5:7], record.occurred_at[8:10]
        event_rel = f"{project_rel}/events/{year}/{month}/{day}/{record.event_id}.md"
        event_link = atlas_links.markdown_link(record.event_id, event_rel, from_file_rel)
        lines = [
            f"## {record.occurred_at[:10]} — {record.title or record.event_id}",
            "",
            f"- Event: {event_link}",
            f"- Type: {record.event_kind}",
        ]
        if record.work_package_id != "unknown":
            wp_rel = f"{project_rel}/work-packages/{record.work_package_id}.md"
            lines.append(
                f"- Work package: "
                f"{atlas_links.markdown_link(record.work_package_id, wp_rel, from_file_rel)}"
            )
        lines.extend(
            [
                f"- Agent: {record.agent}",
                f"- Routed: {record.routed_at}",
                "- Evidence: "
                + atlas_links.markdown_link("raw", record.raw_path, from_file_rel)
                + " · "
                + atlas_links.markdown_link(
                    "normalized", record.normalized_path, from_file_rel
                ),
                f"- Raw SHA-256: `{record.raw_sha256}`",
            ]
        )
        blocks.append("\n".join(lines))
    return "\n\n".join(blocks) if blocks else "No events routed yet."


def render_log_page(
    state: ProjectRoutingState,
    *,
    display_name: str,
    from_file_rel: str,
    project_rel: str,
    existing: str | None,
) -> str:
    """Render the full project-log page, preserving human content."""
    entries = render_log_entries(state, from_file_rel=from_file_rel, project_rel=project_rel)
    if existing is None:
        return (
            "---\n"
            "type: Project Log\n"
            "schema_version: 1\n"
            f'project_id: "{state.project_id}"\n'
            f'title: "{display_name} — Activity Log"\n'
            "---\n\n"
            f"# {display_name} — Activity Log\n\n"
            "Chronological project activity. Newest first. Generated by the\n"
            "Atlas router; do not edit inside ATLAS markers.\n\n"
            + generated_regions.render_region(LOG_REGION, entries)
            + "\n"
        )
    return generated_regions.update_regions(existing, {LOG_REGION: entries})
