import { describe, expect, it, vi } from "vitest";
import generatedPacket from "./test-fixtures/generated-a1-packet.json";
import {
  assertHonestProjection,
  envelopeFromProjection,
  loadProjection,
  ProjectionContractError,
  unavailableEnvelope,
} from "./adapter";
import type { MissionControlProjection, StudioEnvelope, StudioSnapshot } from "../types";

function projection(): MissionControlProjection {
  return structuredClone(generatedPacket) as MissionControlProjection;
}

function snapshot(packet: MissionControlProjection): StudioSnapshot {
  return packet.studio_snapshot as StudioSnapshot;
}

function envelopeAt(packet: MissionControlProjection, nowMs: number): StudioEnvelope {
  return (envelopeFromProjection as unknown as (
    value: MissionControlProjection,
    localNowMs: number,
  ) => StudioEnvelope)(packet, nowMs);
}

describe("Studio projection boundary", () => {
  it("accepts a complete packet generated by the repository A1 builder", () => {
    expect(() => assertHonestProjection(projection())).not.toThrow();
  });

  it("rejects malformed embedded A0 control-view content", () => {
    const packet = projection();
    const controlView = snapshot(packet).panels.control_view.body;
    expect(controlView).not.toBeNull();
    delete (controlView as unknown as Record<string, unknown>).view_fingerprint;

    expect(() => assertHonestProjection(packet)).toThrow(ProjectionContractError);
  });

  it("rejects an unsupported nested telemetry schema", () => {
    const packet = projection();
    const telemetry = snapshot(packet).panels.telemetry.body;
    expect(telemetry).not.toBeNull();
    (telemetry as unknown as Record<string, unknown>).schema = "ATLAS_COORDINATION_TELEMETRY_V2";

    expect(() => assertHonestProjection(packet)).toThrow(/telemetry/i);
  });

  it("fails closed when any nested honesty flag is false", () => {
    const packet = projection();
    const controlView = snapshot(packet).panels.control_view.body;
    expect(controlView).not.toBeNull();
    controlView!.honesty.control_view_ne_authority = false as never;

    expect(() => assertHonestProjection(packet)).toThrow(/honesty/i);
  });

  it("rejects authority-bearing attention", () => {
    const packet = projection();
    packet.attention[0] = { ...packet.attention[0], authorized: true };

    expect(() => assertHonestProjection(packet)).toThrow(/attention/i);
  });

  it("uses source time and TTL for a separately labelled local age check", () => {
    const packet = projection();
    const originalFreshness = structuredClone(packet.freshness);
    const envelope = envelopeAt(packet, Date.parse("2026-09-09T12:02:01Z"));

    expect(envelope.source.current).toBe(false);
    expect(envelope.source.localFreshness).toEqual({
      state: "STALE",
      ageSeconds: 121,
      checkedAtUtc: "2026-09-09T12:02:01.000Z",
      label: "LOCAL AGE CHECK",
    });
    expect(envelope.source.label).toContain("LOCAL");
    expect(packet.freshness).toEqual(originalFreshness);
  });

  it.each(["STALE", "OFFLINE", "UNKNOWN"] as const)(
    "never labels source-supplied %s projection current",
    (state) => {
      const packet = projection();
      packet.freshness.state = state;
      const envelope = envelopeAt(packet, Date.parse(packet.freshness.generated_at_utc));

      expect(envelope.source.current).toBe(false);
      expect(envelope.source.label).toContain(state);
      expect(envelope.source.detail).toContain("never promoted to healthy");
    },
  );

  it("rejects an unparseable LIVE freshness timestamp", () => {
    const packet = projection();
    packet.freshness.generated_at_utc = "not-a-timestamp";

    expect(() => assertHonestProjection(packet)).toThrow(/freshness/i);
  });

  it("loads the complete validated packet without transforming source evidence", async () => {
    const packet = projection();
    vi.stubGlobal("fetch", vi.fn().mockResolvedValue(
      new Response(JSON.stringify(packet), { status: 200 }),
    ));

    const envelope = await (loadProjection as unknown as (
      signal?: AbortSignal,
      localNowMs?: number,
    ) => Promise<StudioEnvelope>)(undefined, Date.parse(packet.generated_at_utc));

    expect(envelope.projection).toEqual(packet);
    expect(envelope.projection).not.toBe(packet);
    vi.unstubAllGlobals();
  });

  it("checks local freshness when the response is received", async () => {
    vi.useFakeTimers();
    vi.setSystemTime("2026-09-09T12:00:00Z");
    let resolveResponse!: (response: Response) => void;
    const pending = new Promise<Response>((resolve) => {
      resolveResponse = resolve;
    });
    vi.stubGlobal("fetch", vi.fn().mockReturnValue(pending));
    const loading = loadProjection();

    vi.setSystemTime("2026-09-09T12:00:05Z");
    resolveResponse(new Response(JSON.stringify(projection()), { status: 200 }));
    const envelope = await loading;

    expect(envelope.source.localFreshness?.ageSeconds).toBe(5);
    vi.useRealTimers();
    vi.unstubAllGlobals();
  });

  it("keeps unavailable live data visibly isolated from design fixtures", () => {
    const envelope = unavailableEnvelope("Bridge returned 503");
    expect(envelope.source.kind).toBe("UNAVAILABLE");
    expect(envelope.source.current).toBe(false);
    expect(envelope.preview).toBeUndefined();
    expect(envelope.source.detail).toContain("Bridge returned 503");
  });
});


it("explains allowlisted bridge failures without reflecting untrusted diagnostic text", async () => {
  vi.stubGlobal("fetch", vi.fn().mockResolvedValue({ok:false,status:503,json:async()=>({reason:"PROJECTION_FAILED_UPSTREAM_READS", diagnostic_ref:"ATLAS-STUDIO-PROJECTION_FAILED_UPSTREAM_READS"})}));
  await expect(loadProjection()).rejects.toThrow("Diagnostic reference: ATLAS-STUDIO-PROJECTION_FAILED_UPSTREAM_READS");
  vi.stubGlobal("fetch", vi.fn().mockResolvedValue({ok:false,status:503,json:async()=>({reason:"credential-canary"})}));
  await expect(loadProjection()).rejects.toThrow("Bridge returned 503");
  vi.unstubAllGlobals();
});


it("does not label a future source timestamp current", () => {
  const envelope = envelopeFromProjection(projection(), Date.parse("2026-09-09T11:59:00Z"));
  expect(envelope.source.current).toBe(false);
  expect(envelope.source.localFreshness?.state).toBe("UNKNOWN");
});
