"""Project Atlas domain model (Epic B).

Import the record types from here rather than the individual modules:

    from project_atlas.domain import SourceRecord, ConceptRecord, Claim, ...
"""

from project_atlas.domain.authority_semantics import (
    ArtifactRole,
    AuthoritativeStateRecord,
    AuthorityDisposition,
    AuthorityDomainId,
    AuthorityEvidence,
)
from project_atlas.domain.claims import Claim, ProvenanceReference
from project_atlas.domain.concepts import (
    ConceptLifecycle,
    ConceptPortfolio,
    ConceptRecord,
    GeneratedMetadata,
    VerificationMetadata,
)
from project_atlas.domain.conflicts import ConflictingClaim, ConflictRecord, ConflictState
from project_atlas.domain.diagnostics import CanonicalImpact, Diagnostic, DiagnosticCode
from project_atlas.domain.findings import ValidationFinding
from project_atlas.domain.parser_output import (
    AmbiguityStatus,
    LocatorConfidence,
    LocatorKind,
    ParserOutput,
    SourceSpan,
)
from project_atlas.domain.relationships import Relationship, RelationType
from project_atlas.domain.semantic import (
    AgentEventReference,
    AuthorityRecord,
    ClaimLifecycleRecord,
    ClaimLifecycleTransition,
    CoverageRecord,
    DecisionRecord,
    ProjectRecord,
    ReviewEntry,
    SourceAuthority,
    SourceLifecycleRecord,
    ValidationEvidence,
    WorkPackageRecord,
)
from project_atlas.domain.semantic_subject import (
    SEMANTIC_SUBJECT_PATTERN,
    SUBJECT_KEY_MAX_LENGTH,
    SUBJECT_KEY_PATTERN,
    SemanticSubject,
    SemanticSubjectError,
    SemanticSubjectKind,
    is_semantic_subject_serialized,
    normalize_subject_key,
)
from project_atlas.domain.source_registry import PathHistoryEntry, SourceLineageRecord
from project_atlas.domain.sources import RepositoryInfo, SourceRecord
from project_atlas.domain.temporal import (
    CurrentStateRecord,
    ResolutionBasis,
    TemporalEvidenceKind,
    TemporalRelation,
    TemporalRelationKind,
    TemporalStatus,
)
from project_atlas.domain.vocabulary import (
    AuthorityLevel,
    ClaimLifecycle,
    ClaimType,
    ClassificationState,
    ConceptType,
    ConfidenceState,
    ConflictType,
    DocumentLifecycle,
    KnowledgeState,
    LifecycleStatus,
    Maturity,
    ReviewCategory,
    ReviewEntryStatus,
    ReviewState,
    Severity,
    SourceChangeState,
    ValidationGate,
)

__all__ = [
    "SEMANTIC_SUBJECT_PATTERN",
    "SUBJECT_KEY_MAX_LENGTH",
    "SUBJECT_KEY_PATTERN",
    "AgentEventReference",
    "AmbiguityStatus",
    "ArtifactRole",
    "AuthoritativeStateRecord",
    "AuthorityDisposition",
    "AuthorityDomainId",
    "AuthorityEvidence",
    "AuthorityLevel",
    "AuthorityRecord",
    "CanonicalImpact",
    "Claim",
    "ClaimLifecycle",
    "ClaimLifecycleRecord",
    "ClaimLifecycleTransition",
    "ClaimType",
    "ClassificationState",
    "ConceptLifecycle",
    "ConceptPortfolio",
    "ConceptRecord",
    "ConceptType",
    "ConfidenceState",
    "ConflictRecord",
    "ConflictState",
    "ConflictType",
    "ConflictingClaim",
    "CoverageRecord",
    "CurrentStateRecord",
    "DecisionRecord",
    "Diagnostic",
    "DiagnosticCode",
    "DocumentLifecycle",
    "GeneratedMetadata",
    "KnowledgeState",
    "LifecycleStatus",
    "LocatorConfidence",
    "LocatorKind",
    "Maturity",
    "ParserOutput",
    "PathHistoryEntry",
    "ProjectRecord",
    "ProvenanceReference",
    "RelationType",
    "Relationship",
    "RepositoryInfo",
    "ResolutionBasis",
    "ReviewCategory",
    "ReviewEntry",
    "ReviewEntryStatus",
    "ReviewState",
    "SemanticSubject",
    "SemanticSubjectError",
    "SemanticSubjectKind",
    "Severity",
    "SourceAuthority",
    "SourceChangeState",
    "SourceLifecycleRecord",
    "SourceLineageRecord",
    "SourceRecord",
    "SourceSpan",
    "TemporalEvidenceKind",
    "TemporalRelation",
    "TemporalRelationKind",
    "TemporalStatus",
    "ValidationEvidence",
    "ValidationFinding",
    "ValidationGate",
    "VerificationMetadata",
    "WorkPackageRecord",
    "is_semantic_subject_serialized",
    "normalize_subject_key",
]
