"""Atlas Studio — A0 snapshot + A1 Mission Control (AS-STUDIO-A0/A1).

STUDIO_UI != AUTHORITY
ATLAS_DAEMON = AUTHORITATIVE_RUNTIME
UI_STATE = PROJECTION_OF_ATLAS_TRUTH
NO_CLI_TEXT_PARSING_AS_PROTOCOL
NO_WHOLESALE_CORE_REWRITE
REUSE_BEFORE_REIMPLEMENT
MODEL_PROVIDER != ATLAS_ARCHITECTURE
STUDIO_CRASH != AGENT_TASK_TERMINATION
ATTENTION != AUTHORIZATION
STALE != CURRENT
UNKNOWN != HEALTHY

Read-only only: no claim / dispatch / emit / merge / vault write APIs.
O1: in-process atlas_dag builders are authoritative RO runtime for A1.
O6: seal/evidence may be UNKNOWN/deferred — never promote to healthy.
"""

__version__ = "0.2.0"

# Honesty design laws (must remain True; mirrored in snapshot/MC honesty blocks).
STUDIO_UI_NE_AUTHORITY = True
ATLAS_DAEMON_IS_AUTHORITATIVE_RUNTIME = True
UI_STATE_IS_PROJECTION = True
NO_CLI_TEXT_PARSING_AS_PROTOCOL = True
NO_WHOLESALE_CORE_REWRITE = True
REUSE_BEFORE_REIMPLEMENT = True
MODEL_PROVIDER_NE_ATLAS_ARCHITECTURE = True
STUDIO_CRASH_NE_AGENT_TASK_TERMINATION = True
GRANTS_NO_MUTATION = True
ATTENTION_NE_AUTHORIZATION = True
STALE_NE_CURRENT = True
UNKNOWN_NE_HEALTHY = True
NESTED_HONESTY_FAIL_CLOSED = True
O1_IN_PROCESS_ATLAS_DAG_RO_RUNTIME = True
O6_SEAL_EVIDENCE_MAY_BE_UNKNOWN = True
