"""Atlas Studio A0 — Linux read-only projection slice (AS-STUDIO-A0-001).

STUDIO_UI != AUTHORITY
ATLAS_DAEMON = AUTHORITATIVE_RUNTIME
UI_STATE = PROJECTION_OF_ATLAS_TRUTH
NO_CLI_TEXT_PARSING_AS_PROTOCOL
NO_WHOLESALE_CORE_REWRITE
REUSE_BEFORE_REIMPLEMENT
MODEL_PROVIDER != ATLAS_ARCHITECTURE
STUDIO_CRASH != AGENT_TASK_TERMINATION

Read-only only: no claim / dispatch / emit / merge / vault write APIs.
"""

__version__ = "0.1.0"

# Honesty design laws (must remain True; mirrored in snapshot honesty block).
STUDIO_UI_NE_AUTHORITY = True
ATLAS_DAEMON_IS_AUTHORITATIVE_RUNTIME = True
UI_STATE_IS_PROJECTION = True
NO_CLI_TEXT_PARSING_AS_PROTOCOL = True
NO_WHOLESALE_CORE_REWRITE = True
REUSE_BEFORE_REIMPLEMENT = True
MODEL_PROVIDER_NE_ATLAS_ARCHITECTURE = True
STUDIO_CRASH_NE_AGENT_TASK_TERMINATION = True
GRANTS_NO_MUTATION = True
