"""Atlas 2.0 derived intelligence (read-only, non-authoritative).

Import from this package, not from ``project_atlas.domain``. These types are
not Layer B records and must not be written as canonical truth.
"""

from project_atlas.intelligence.agent_context import (
    DerivedAgentContext,
    compose_agent_context,
)
from project_atlas.intelligence.boundary import (
    AUTO_RESOLVE_CONTRADICTIONS,
    CONFIDENCE_SCORE_IS_FACT,
    CONTRADICTION_CANDIDATE_IS_PROVEN_FALSEHOOD,
    DERIVED_INTELLIGENCE_IS_AUTHORITY,
    DERIVED_STATE_WRITES_CANONICAL_TRUTH,
    NEXT_ACTION_CANDIDATE_IS_COMMAND,
    PACKAGE_CTX_001,
    PACKAGE_HANDOFF_001,
    PACKAGE_INTEL_001,
    PACKAGE_INTEL_002,
    PACKAGE_INTEL_003,
    PACKAGE_INTEL_004,
    PACKAGE_INTEL_005,
    PACKAGE_NEXT_001,
    PACKAGE_PORTFOLIO_001,
    PACKAGE_PORTFOLIO_002,
    PACKAGE_PORTFOLIO_003,
    PACKAGE_STATE_001,
    PROJECT_STATE_IS_CANONICAL,
    TRUTH_BOUNDARY_CONTRADICTION,
    TRUTH_BOUNDARY_CTX,
    TRUTH_BOUNDARY_EVIDENCE,
    TRUTH_BOUNDARY_EXPLAIN,
    TRUTH_BOUNDARY_GAPS,
    TRUTH_BOUNDARY_HANDOFF,
    TRUTH_BOUNDARY_NEXT,
    TRUTH_BOUNDARY_PORTFOLIO,
    TRUTH_BOUNDARY_QUERY,
    TRUTH_BOUNDARY_STATE,
    UNKNOWN_IS_VALID,
)
from project_atlas.intelligence.change import (
    ChangeClass,
    SemanticChange,
    detect_semantic_changes,
)
from project_atlas.intelligence.contradictions import (
    ContradictionCandidate,
    ContradictionClass,
    ContradictionContext,
    PairingStats,
    SeverityClass,
    TemporalRelationship,
    find_contradiction_candidates,
    find_contradiction_candidates_report,
)
from project_atlas.intelligence.delta import DeltaPolarity, ValueDelta, classify_deltas
from project_atlas.intelligence.derived_state import (
    AttentionCandidate,
    AttentionKind,
    DerivedFact,
    DerivedProjectState,
    FactStatus,
    StateContext,
    synthesize_project_state,
)
from project_atlas.intelligence.evidence import assess_evidence, assess_evidence_many
from project_atlas.intelligence.explain import EvidenceTrace, explain_why
from project_atlas.intelligence.explain_graph import (
    ExplanationEdge,
    ExplanationGraph,
    ExplanationNode,
    build_explanation_graph,
)
from project_atlas.intelligence.gaps import (
    EvidenceGap,
    GapClass,
    GapCurrentStatus,
    detect_evidence_gaps,
)
from project_atlas.intelligence.handoff import EvidenceHandoff, compose_evidence_handoff
from project_atlas.intelligence.next_action import (
    NextActionCandidate,
    NextActionKind,
    propose_next_action_candidates,
)
from project_atlas.intelligence.observe import (
    IntelligenceRunReport,
    observe_intelligence_run,
)
from project_atlas.intelligence.portfolio import (
    LeakageRejection,
    PortfolioProjectEntry,
    PortfolioState,
    aggregate_portfolio_state,
)
from project_atlas.intelligence.portfolio_attention import (
    AttentionRankClass,
    PortfolioAttentionEntry,
    rank_portfolio_attention,
)
from project_atlas.intelligence.portfolio_deps import (
    DependencyClass,
    PortfolioDependency,
    detect_portfolio_dependencies,
)
from project_atlas.intelligence.query import (
    IntelligenceAnswer,
    IntelligenceQuery,
    IntelligenceQueryKind,
    QueryOutcome,
    SlotStatus,
    query_intelligence,
)
from project_atlas.intelligence.risk import RiskClass, RiskSignal, detect_risk_signals
from project_atlas.intelligence.types import (
    AssessableClaim,
    AssessmentContext,
    ConfidenceClass,
    EvidenceAssessment,
    EvidenceDimensions,
    EvidenceRef,
    EvidenceRole,
    LimitingFactor,
    LineageIntegrity,
    SourceObservation,
    ValidityWindowInput,
)

__all__ = [
    "AUTO_RESOLVE_CONTRADICTIONS",
    "CONFIDENCE_SCORE_IS_FACT",
    "CONTRADICTION_CANDIDATE_IS_PROVEN_FALSEHOOD",
    "DERIVED_INTELLIGENCE_IS_AUTHORITY",
    "DERIVED_STATE_WRITES_CANONICAL_TRUTH",
    "NEXT_ACTION_CANDIDATE_IS_COMMAND",
    "PACKAGE_CTX_001",
    "PACKAGE_HANDOFF_001",
    "PACKAGE_INTEL_001",
    "PACKAGE_INTEL_002",
    "PACKAGE_INTEL_003",
    "PACKAGE_INTEL_004",
    "PACKAGE_INTEL_005",
    "PACKAGE_NEXT_001",
    "PACKAGE_PORTFOLIO_001",
    "PACKAGE_PORTFOLIO_002",
    "PACKAGE_PORTFOLIO_003",
    "PACKAGE_STATE_001",
    "PROJECT_STATE_IS_CANONICAL",
    "TRUTH_BOUNDARY_CONTRADICTION",
    "TRUTH_BOUNDARY_CTX",
    "TRUTH_BOUNDARY_EVIDENCE",
    "TRUTH_BOUNDARY_EXPLAIN",
    "TRUTH_BOUNDARY_GAPS",
    "TRUTH_BOUNDARY_HANDOFF",
    "TRUTH_BOUNDARY_NEXT",
    "TRUTH_BOUNDARY_PORTFOLIO",
    "TRUTH_BOUNDARY_QUERY",
    "TRUTH_BOUNDARY_STATE",
    "UNKNOWN_IS_VALID",
    "AssessableClaim",
    "AssessmentContext",
    "AttentionCandidate",
    "AttentionKind",
    "AttentionRankClass",
    "ChangeClass",
    "ConfidenceClass",
    "ContradictionCandidate",
    "ContradictionClass",
    "ContradictionContext",
    "DeltaPolarity",
    "DependencyClass",
    "DerivedAgentContext",
    "DerivedFact",
    "DerivedProjectState",
    "EvidenceAssessment",
    "EvidenceDimensions",
    "EvidenceGap",
    "EvidenceHandoff",
    "EvidenceRef",
    "EvidenceRole",
    "EvidenceTrace",
    "ExplanationEdge",
    "ExplanationGraph",
    "ExplanationNode",
    "FactStatus",
    "GapClass",
    "GapCurrentStatus",
    "IntelligenceAnswer",
    "IntelligenceQuery",
    "IntelligenceQueryKind",
    "IntelligenceRunReport",
    "LeakageRejection",
    "LimitingFactor",
    "LineageIntegrity",
    "NextActionCandidate",
    "NextActionKind",
    "PairingStats",
    "PortfolioAttentionEntry",
    "PortfolioDependency",
    "PortfolioProjectEntry",
    "PortfolioState",
    "QueryOutcome",
    "RiskClass",
    "RiskSignal",
    "SemanticChange",
    "SeverityClass",
    "SlotStatus",
    "SourceObservation",
    "StateContext",
    "TemporalRelationship",
    "ValidityWindowInput",
    "ValueDelta",
    "aggregate_portfolio_state",
    "assess_evidence",
    "assess_evidence_many",
    "build_explanation_graph",
    "classify_deltas",
    "compose_agent_context",
    "compose_evidence_handoff",
    "detect_evidence_gaps",
    "detect_portfolio_dependencies",
    "detect_risk_signals",
    "detect_semantic_changes",
    "explain_why",
    "find_contradiction_candidates",
    "find_contradiction_candidates_report",
    "observe_intelligence_run",
    "propose_next_action_candidates",
    "query_intelligence",
    "rank_portfolio_attention",
    "synthesize_project_state",
]
