"""Atlas 2.0 derived intelligence (read-only, non-authoritative).

Import from this package, not from ``project_atlas.domain``. These types are
not Layer B records and must not be written as canonical truth.
"""

from project_atlas.intelligence.boundary import (
    AUTO_RESOLVE_CONTRADICTIONS,
    CONFIDENCE_SCORE_IS_FACT,
    CONTRADICTION_CANDIDATE_IS_PROVEN_FALSEHOOD,
    DERIVED_INTELLIGENCE_IS_AUTHORITY,
    DERIVED_STATE_WRITES_CANONICAL_TRUTH,
    PACKAGE_INTEL_001,
    PACKAGE_INTEL_002,
    PACKAGE_INTEL_003,
    PACKAGE_INTEL_004,
    PACKAGE_INTEL_005,
    PACKAGE_STATE_001,
    PROJECT_STATE_IS_CANONICAL,
    TRUTH_BOUNDARY_CONTRADICTION,
    TRUTH_BOUNDARY_EVIDENCE,
    TRUTH_BOUNDARY_EXPLAIN,
    TRUTH_BOUNDARY_GAPS,
    TRUTH_BOUNDARY_QUERY,
    TRUTH_BOUNDARY_STATE,
    UNKNOWN_IS_VALID,
)
from project_atlas.intelligence.contradictions import (
    ContradictionCandidate,
    ContradictionClass,
    ContradictionContext,
    PairingStats,
    SeverityClass,
    TemporalRelationship,
    find_contradiction_candidates,
    find_contradiction_candidates_report,
)
from project_atlas.intelligence.derived_state import (
    AttentionCandidate,
    AttentionKind,
    DerivedFact,
    DerivedProjectState,
    FactStatus,
    StateContext,
    synthesize_project_state,
)
from project_atlas.intelligence.evidence import assess_evidence, assess_evidence_many
from project_atlas.intelligence.explain import EvidenceTrace, explain_why
from project_atlas.intelligence.gaps import (
    EvidenceGap,
    GapClass,
    GapCurrentStatus,
    detect_evidence_gaps,
)
from project_atlas.intelligence.query import (
    IntelligenceAnswer,
    IntelligenceQuery,
    IntelligenceQueryKind,
    QueryOutcome,
    SlotStatus,
    query_intelligence,
)
from project_atlas.intelligence.types import (
    AssessableClaim,
    AssessmentContext,
    ConfidenceClass,
    EvidenceAssessment,
    EvidenceDimensions,
    EvidenceRef,
    EvidenceRole,
    LimitingFactor,
    LineageIntegrity,
    SourceObservation,
    ValidityWindowInput,
)

__all__ = [
    "AUTO_RESOLVE_CONTRADICTIONS",
    "CONFIDENCE_SCORE_IS_FACT",
    "CONTRADICTION_CANDIDATE_IS_PROVEN_FALSEHOOD",
    "DERIVED_INTELLIGENCE_IS_AUTHORITY",
    "DERIVED_STATE_WRITES_CANONICAL_TRUTH",
    "PACKAGE_INTEL_001",
    "PACKAGE_INTEL_002",
    "PACKAGE_INTEL_003",
    "PACKAGE_INTEL_004",
    "PACKAGE_INTEL_005",
    "PACKAGE_STATE_001",
    "PROJECT_STATE_IS_CANONICAL",
    "TRUTH_BOUNDARY_CONTRADICTION",
    "TRUTH_BOUNDARY_EVIDENCE",
    "TRUTH_BOUNDARY_EXPLAIN",
    "TRUTH_BOUNDARY_GAPS",
    "TRUTH_BOUNDARY_QUERY",
    "TRUTH_BOUNDARY_STATE",
    "UNKNOWN_IS_VALID",
    "AssessableClaim",
    "AssessmentContext",
    "AttentionCandidate",
    "AttentionKind",
    "ConfidenceClass",
    "ContradictionCandidate",
    "ContradictionClass",
    "ContradictionContext",
    "DerivedFact",
    "DerivedProjectState",
    "EvidenceAssessment",
    "EvidenceDimensions",
    "EvidenceGap",
    "EvidenceRef",
    "EvidenceRole",
    "EvidenceTrace",
    "FactStatus",
    "GapClass",
    "GapCurrentStatus",
    "IntelligenceAnswer",
    "IntelligenceQuery",
    "IntelligenceQueryKind",
    "LimitingFactor",
    "LineageIntegrity",
    "PairingStats",
    "QueryOutcome",
    "SeverityClass",
    "SlotStatus",
    "SourceObservation",
    "StateContext",
    "TemporalRelationship",
    "ValidityWindowInput",
    "assess_evidence",
    "assess_evidence_many",
    "detect_evidence_gaps",
    "explain_why",
    "find_contradiction_candidates",
    "find_contradiction_candidates_report",
    "query_intelligence",
    "synthesize_project_state",
]
