"""Truth-boundary constants for Atlas 2.0 derived intelligence.

AS-2.0-INTEL-001 / AS-2.0-INTEL-002 / AS-2.0-STATE-001.

Derived intelligence is explainable and provenance-traceable. It is never
canonical Layer B truth, never a write-back engine, and never a substitute
for human review.
"""

from __future__ import annotations

from typing import Final

PACKAGE_INTEL_001: Final[str] = "AS-2.0-INTEL-001"
PACKAGE_INTEL_002: Final[str] = "AS-2.0-INTEL-002"
PACKAGE_INTEL_003: Final[str] = "AS-2.0-INTEL-003"
PACKAGE_INTEL_004: Final[str] = "AS-2.0-INTEL-004"
PACKAGE_INTEL_005: Final[str] = "AS-2.0-INTEL-005"
PACKAGE_STATE_001: Final[str] = "AS-2.0-STATE-001"
PACKAGE_CHANGE_001: Final[str] = "AS-2.0-CHANGE-001"
PACKAGE_RISK_001: Final[str] = "AS-2.0-RISK-001"
PACKAGE_DELTA_001: Final[str] = "AS-2.0-DELTA-001"
PACKAGE_CTX_001: Final[str] = "AS-2.0-CTX-001"
PACKAGE_HANDOFF_001: Final[str] = "AS-2.0-HANDOFF-001"
PACKAGE_NEXT_001: Final[str] = "AS-2.0-NEXT-001"
PACKAGE_PORTFOLIO_001: Final[str] = "AS-2.0-PORTFOLIO-001"
PACKAGE_PORTFOLIO_002: Final[str] = "AS-2.0-PORTFOLIO-002"
PACKAGE_PORTFOLIO_003: Final[str] = "AS-2.0-PORTFOLIO-003"
PACKAGE_PERF_002: Final[str] = "AS-2.0-INTEL-PERF-002"

DERIVED_INTELLIGENCE_IS_AUTHORITY: Final[str] = "NO"
DERIVED_STATE_WRITES_CANONICAL_TRUTH: Final[str] = "NO"
CONTRADICTION_CANDIDATE_IS_PROVEN_FALSEHOOD: Final[str] = "NO"
CONFIDENCE_SCORE_IS_FACT: Final[str] = "NO"
UNKNOWN_IS_VALID: Final[str] = "YES"
PROJECT_STATE_IS_CANONICAL: Final[str] = "NO"
AUTO_RESOLVE_CONTRADICTIONS: Final[str] = "NO"
NEXT_ACTION_CANDIDATE_IS_COMMAND: Final[str] = "NO"
RISK_SIGNAL_IS_FACT: Final[str] = "NO"
CANONICAL_WRITE: Final[str] = "NO"

TRUTH_BOUNDARY_EVIDENCE: Final[str] = (
    "EVIDENCE ASSESSMENT ≠ AUTHORITY / ≠ CLAIM MUTATION / ≠ PROBABILITY"
)
TRUTH_BOUNDARY_CONTRADICTION: Final[str] = (
    "CONTRADICTION CANDIDATE ≠ PROVEN FALSEHOOD / ≠ AUTO-RESOLUTION / ≠ AUTHORITY"
)
TRUTH_BOUNDARY_STATE: Final[str] = (
    "DERIVED PROJECT STATE ≠ CANONICAL TRUTH / ≠ ROADMAP / ≠ HEALTH SCORE"
)
TRUTH_BOUNDARY_QUERY: Final[str] = (
    "INTELLIGENCE QUERY ≠ AUTHORITY / ≠ LIVE API / ≠ CANONICAL WRITE"
)
TRUTH_BOUNDARY_EXPLAIN: Final[str] = (
    "EXPLAIN-WHY ≠ AUTHORITY / ≠ NEW EVIDENCE / ≠ RESOLUTION"
)
TRUTH_BOUNDARY_GAPS: Final[str] = (
    "EVIDENCE GAP ≠ MISSING TRUTH / ≠ COMMAND TO INVENT EVIDENCE"
)
TRUTH_BOUNDARY_CHANGE: Final[str] = "SEMANTIC CHANGE ≠ REGRESSION / ≠ AUTHORITY"
TRUTH_BOUNDARY_RISK: Final[str] = "RISK SIGNAL ≠ FACT / ATTENTION ≠ FAILURE"
TRUTH_BOUNDARY_DELTA: Final[str] = "DELTA POLARITY ≠ SCORE / UNKNOWN ≠ SAFE"
TRUTH_BOUNDARY_CTX: Final[str] = (
    "DERIVED AGENT CONTEXT ≠ AUTHORITY / ≠ FIXTURE CONTEXT PACK / ≠ COMMAND"
)
TRUTH_BOUNDARY_HANDOFF: Final[str] = (
    "EVIDENCE HANDOFF ≠ COMMAND / ≠ CANONICAL WRITE / ≠ AUTO-RESOLVE"
)
TRUTH_BOUNDARY_NEXT: Final[str] = (
    "NEXT-ACTION CANDIDATE ≠ COMMAND / ≠ EXECUTION / ≠ AUTHORITY"
)
TRUTH_BOUNDARY_PORTFOLIO: Final[str] = (
    "PORTFOLIO AGGREGATE ≠ CROSS-PROJECT TRUTH / ≠ PRIORITY SCORE"
)

GENERATED_BY: Final[str] = "project-atlas"
