"""Vault scaffold generation for ``atlas init`` (FR-001, AT-001).

Creates the three-layer OKF vault skeleton from `docs/plan.md` section 3:
system, portfolio, project, capability, infrastructure, technology,
decision, standards, source, generated, and template areas.

Safety and determinism rules:

- unsafe output paths (filesystem root, user home, existing non-empty
  targets) are rejected before anything is written — fail closed;
- files are written atomically (temp file + ``os.replace``);
- content is fully deterministic: no wall-clock timestamps, fixed file
  set, fixed ordering (NFR-001);
- ``--dry-run`` reports the plan without touching the filesystem.
"""

from __future__ import annotations

import contextlib
import os
import tempfile
from dataclasses import dataclass
from pathlib import Path, PurePosixPath

from project_atlas.logging import get_logger

_log = get_logger("scaffold")

GENERATOR_ID = "agent:atlas-init"

#: Directories created (in this order) below the vault root. Derived from
#: the vault structure in docs/plan.md section 3.
DIRECTORIES: tuple[str, ...] = (
    "00-system",
    "01-portfolio",
    "projects",
    "capabilities",
    "infrastructure",
    "infrastructure/hosts",
    "infrastructure/networks",
    "infrastructure/services",
    "infrastructure/environments",
    "infrastructure/storage",
    "infrastructure/deployment-targets",
    "technologies",
    "technologies/frameworks",
    "technologies/databases",
    "technologies/ai-models",
    "technologies/infrastructure-tools",
    "technologies/development-tools",
    "decisions",
    "decisions/cross-project",
    "standards",
    "sources",
    "sources/repositories",
    "sources/imported-documents",
    "sources/reports",
    "sources/manifests",
    "generated",
    "generated/dashboards",
    "generated/reports",
    "generated/maps",
    "generated/quality-controls",
    "templates",
)

_SYSTEM_NOTES: tuple[str, ...] = (
    "vault-charter",
    "taxonomy",
    "metadata-schema",
    "ingestion-policy",
    "trust-policy",
    "lifecycle-policy",
    "linking-policy",
    "naming-conventions",
)

_TEMPLATES: tuple[str, ...] = (
    "project",
    "component",
    "decision",
    "milestone",
    "risk",
    "validation",
    "deployment",
    "runbook",
    "source-document",
)

_AREA_TITLES: dict[str, str] = {
    "": "Project Atlas Vault",
    "00-system": "System",
    "01-portfolio": "Portfolio",
    "projects": "Projects",
    "capabilities": "Capabilities",
    "infrastructure": "Infrastructure",
    "technologies": "Technologies",
    "decisions": "Decisions",
    "standards": "Standards",
    "sources": "Sources",
}


class ScaffoldError(Exception):
    """Raised when the scaffold cannot be created safely."""


@dataclass(frozen=True)
class ScaffoldPlan:
    """Deterministic description of everything ``atlas init`` will create."""

    root: Path
    directories: tuple[str, ...]
    files: tuple[tuple[str, str], ...]  # (vault-relative POSIX path, content)


def _frontmatter(note_type: str, title: str) -> str:
    # Deterministic by design: no timestamps (NFR-001, ADR-001).
    return f"---\ntype: {note_type}\ntitle: {title}\ngenerated:\n  by: {GENERATOR_ID}\n---\n"


def _index_content(area: str) -> str:
    title = _AREA_TITLES[area]
    return (
        f"{_frontmatter('Index', title)}\n"
        f"# {title}\n\n"
        "_Generated scaffold index. Populated by `atlas build-indexes`._\n"
    )


def _system_note_content(name: str) -> str:
    title = name.replace("-", " ").title()
    return (
        f"{_frontmatter('Standard', title)}\n"
        f"# {title}\n\n"
        "<!-- BEGIN HUMAN: policy -->\n"
        "Define this policy before ingesting sources.\n"
        "<!-- END HUMAN: policy -->\n"
    )


def _template_content(name: str) -> str:
    title = name.replace("-", " ").title()
    return (
        f"{_frontmatter(title, f'{title} template')}\n"
        f"# {title}\n\n"
        "<!-- BEGIN GENERATED: summary -->\n"
        "<!-- END GENERATED: summary -->\n\n"
        "<!-- BEGIN HUMAN: notes -->\n"
        "<!-- END HUMAN: notes -->\n"
    )


def _readme_content() -> str:
    return (
        "# Project Atlas Vault\n\n"
        "Generated by Project Atlas. Plain Markdown with YAML frontmatter; "
        "readable without Obsidian (NFR-003).\n\n"
        "- `00-system/` — vault constitution and policies\n"
        "- `01-portfolio/` — cross-project intelligence (Layer C)\n"
        "- `projects/` — canonical project bundles (Layer B)\n"
        "- `sources/` — imported source evidence (Layer A)\n"
        "- `templates/` — concept note templates\n"
    )


def _log_content() -> str:
    return (
        f"{_frontmatter('Index', 'Vault Log')}\n"
        "# Vault Log\n\n"
        "_Chronological vault updates. Newest first._\n"
    )


def build_plan(root: Path) -> ScaffoldPlan:
    """Compute the full scaffold plan for ``root`` without writing anything."""
    files: list[tuple[str, str]] = [
        ("index.md", _index_content("")),
        ("log.md", _log_content()),
        ("README.md", _readme_content()),
    ]
    for area in sorted(_AREA_TITLES):
        if area:
            files.append((f"{area}/index.md", _index_content(area)))
    files.extend((f"00-system/{name}.md", _system_note_content(name)) for name in _SYSTEM_NOTES)
    files.extend((f"templates/{name}.md", _template_content(name)) for name in _TEMPLATES)
    return ScaffoldPlan(root=root, directories=DIRECTORIES, files=tuple(files))


def validate_output_path(path: Path) -> Path:
    """Resolve and safety-check the output path (fail closed, AT-013 posture).

    Rejects: the filesystem root, the user's home directory, existing
    files, and existing non-empty directories.
    """
    try:
        resolved = path.expanduser().resolve(strict=False)
    except OSError as exc:
        raise ScaffoldError(f"unsafe output path {path}: {exc}") from exc

    if resolved == Path(resolved.anchor):
        raise ScaffoldError(f"refusing to use filesystem root as vault: {resolved}")
    home = Path.home().resolve()
    if resolved == home:
        raise ScaffoldError(f"refusing to use home directory as vault: {resolved}")
    if resolved.is_file():
        raise ScaffoldError(f"output path exists and is not a directory: {resolved}")
    if resolved.is_dir() and any(resolved.iterdir()):
        raise ScaffoldError(
            f"output directory is not empty: {resolved} "
            "(overwriting existing content is not supported)"
        )
    return resolved


def _write_atomic(path: Path, content: str) -> None:
    """Write ``content`` atomically: temp file in the same directory, then replace."""
    path.parent.mkdir(parents=True, exist_ok=True)
    fd, tmp_name = tempfile.mkstemp(dir=path.parent, prefix=f".{path.name}.", suffix=".tmp")
    try:
        with os.fdopen(fd, "w", encoding="utf-8", newline="\n") as handle:
            handle.write(content)
        os.replace(tmp_name, path)
    except BaseException:
        with contextlib.suppress(OSError):
            os.unlink(tmp_name)
        raise


def create_scaffold(output: Path, *, dry_run: bool = False) -> ScaffoldPlan:
    """Create (or, with ``dry_run``, only plan) the vault scaffold at ``output``."""
    resolved = validate_output_path(output)
    plan = build_plan(resolved)

    if dry_run:
        _log.info(
            "dry run: no files written",
            extra={"context": {"root": str(resolved), "files": len(plan.files)}},
        )
        return plan

    for directory in plan.directories:
        # Defence in depth: never write outside the vault root.
        target = resolved.joinpath(*PurePosixPath(directory).parts)
        if not target.resolve(strict=False).is_relative_to(resolved):
            raise ScaffoldError(f"refusing to create directory outside vault root: {directory}")
        target.mkdir(parents=True, exist_ok=True)
    for relative, content in plan.files:
        target = resolved.joinpath(*PurePosixPath(relative).parts)
        if not target.resolve(strict=False).is_relative_to(resolved):
            raise ScaffoldError(f"refusing to write outside vault root: {relative}")
        _write_atomic(target, content)

    _log.info(
        "vault scaffold created",
        extra={
            "context": {
                "root": str(resolved),
                "directories": len(plan.directories),
                "files": len(plan.files),
            }
        },
    )
    return plan
